
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

import React from 'react';

export const Footer: React.FC = () => {
  return (
    <footer className="bg-stone-900 dark:bg-black text-stone-400 py-16 transition-colors duration-500">
      <div className="container mx-auto px-6 flex flex-col md:flex-row justify-between items-center gap-8">
          <div className="text-center md:text-left">
              <div className="text-white font-serif font-bold text-2xl mb-2">AlphaQubit</div>
              <p className="text-sm">Visualizing "Learning high-accuracy error decoding for quantum processors"</p>
          </div>
      </div>
      <div className="text-center mt-12 text-xs text-stone-600 dark:text-stone-500">
          Based on research published in Nature (2024). Generated by AI.
      </div>
    </footer>
  );
};
