
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from 'react';
import { APP_CONFIG } from '../../data/content';

export const Footer: React.FC = () => {
  const currentYear = new Date().getFullYear();

  return (
    <footer className="bg-stone-950 text-stone-400 py-24 transition-colors duration-500 border-t border-stone-900">
      <div className="container mx-auto px-6 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-12">
          <div className="col-span-1 lg:col-span-2">
              <div className="text-white font-serif font-bold text-3xl mb-6 flex items-center gap-3">
                <div className="w-8 h-8 rounded-lg bg-nobel-gold flex items-center justify-center text-white text-lg">α</div>
                AlphaQubit
              </div>
              <p className="text-sm leading-relaxed max-w-md text-stone-500">
                Visualizing "Learning high-accuracy error decoding for quantum processors". 
                A design exploration of modern enterprise-grade professional services architecture 
                modeled on federated best-of-breed standards.
              </p>
          </div>
          
          <div>
            <h4 className="text-white font-bold text-xs uppercase tracking-[0.2em] mb-6">Documentation</h4>
            <ul className="space-y-4 text-sm">
              <li><a href={APP_CONFIG.paperLink} target="_blank" rel="noopener" className="hover:text-nobel-gold transition-colors">Nature Publication</a></li>
              <li><a href="#" className="hover:text-nobel-gold transition-colors">Architecture Whitepaper</a></li>
              <li><a href="#" className="hover:text-nobel-gold transition-colors">Integration API Spec</a></li>
            </ul>
          </div>

          <div>
            <h4 className="text-white font-bold text-xs uppercase tracking-[0.2em] mb-6">Compliance</h4>
            <ul className="space-y-4 text-sm">
              <li><a href="#" className="hover:text-nobel-gold transition-colors">Data Residency</a></li>
              <li><a href="#" className="hover:text-nobel-gold transition-colors">Security Controls</a></li>
              <li><a href="#" className="hover:text-nobel-gold transition-colors">Platform Status</a></li>
            </ul>
          </div>
      </div>
      
      <div className="container mx-auto px-6 mt-24 pt-8 border-t border-stone-900 flex flex-col md:flex-row justify-between items-center gap-4 text-[10px] font-bold uppercase tracking-widest text-stone-600">
          <div>© {currentYear} {APP_CONFIG.appName} PLATFORM ARCHITECTURE</div>
          <div className="italic">Based on research published in Nature (2024) • Generated by AI</div>
      </div>
    </footer>
  );
};
